### PR TITLE
RFC on ChronicleStampedLock addition to Chronicle-Algorithms

### PR DESCRIPTION
**Pull request by Cotton-Ben**

### CODE REVIEW

**Comment by RobAustin** [comment]
ben these have conflicts, are you able to reissue without merge conflicts

**Conflicting files**
IPC_Executor/IPC_Executor-0.1.md
Template/Template-0.1.md
WFA/WFA-0.1.md

**Comment by Cotton-Ben** [comment]
Hi Rob, My apologies.  Will effort to resolve immediately.

**Comment by Cotton-Ben** [comment]
Hi Rob. please pull/merge

**Comment by RobAustin** [comment]
thanks

**Pull request merged**
